import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
import { CountrySection } from '@/components/dashboard/CountrySection';
import { MarketIndexCard } from '@/components/dashboard/MarketIndexCard';
import { SearchModal } from '@/components/dashboard/SearchModal';
import { StockCard } from '@/components/dashboard/StockCard';
import { Button } from '@/components/ui/Button';
import { useMarketStore } from '@/store/marketStore';
export function DashboardPage() {
    const { marketIndices, countrySections, trendingStocks, markets, isLoading, error, loadDashboard, refreshDashboard, openSearchModal } = useMarketStore();
    useEffect(() => {
        void loadDashboard();
    }, [loadDashboard]);
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("section", { className: "relative overflow-hidden rounded-3xl border border-slate-200 bg-gradient-to-r from-sky-100 via-cyan-50 to-emerald-100 p-6 shadow-sm", children: [_jsx("div", { className: "absolute -right-16 -top-16 h-40 w-40 rounded-full bg-cyan-300/40 blur-3xl" }), _jsx("div", { className: "absolute -bottom-20 left-20 h-44 w-44 rounded-full bg-emerald-300/40 blur-3xl" }), _jsxs("div", { className: "relative flex flex-col gap-4 md:flex-row md:items-center md:justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-[0.2em] text-slate-600", children: "Global Snapshot" }), _jsx("h1", { className: "mt-1 text-3xl font-bold text-slate-900 md:text-4xl", children: "Financial Dashboard" }), _jsx("p", { className: "mt-2 max-w-2xl text-sm text-slate-700 md:text-base", children: "Track major indices, scan countries, and surface trending symbols from one fast view." })] }), _jsxs("div", { className: "flex gap-3", children: [_jsx(Button, { onClick: () => openSearchModal(), className: "rounded-xl bg-slate-900 px-5 py-2.5 text-white hover:bg-slate-800", children: "Global Search" }), _jsx(Button, { onClick: () => {
                                            void refreshDashboard();
                                        }, className: "rounded-xl bg-white px-5 py-2.5 text-slate-900 ring-1 ring-slate-200 hover:bg-slate-50", children: "Refresh" })] })] })] }), error ? (_jsx("section", { className: "rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700", children: error })) : null, _jsxs("section", { className: "space-y-3", children: [_jsx("h2", { className: "text-xl font-semibold text-slate-900", children: "Market Overview" }), isLoading ? (_jsx("div", { className: "grid gap-3 sm:grid-cols-2 xl:grid-cols-4", children: Array.from({ length: 4 }).map((_, index) => (_jsx("div", { className: "h-36 animate-pulse rounded-2xl bg-slate-200" }, index))) })) : (_jsx("div", { className: "grid gap-3 sm:grid-cols-2 xl:grid-cols-4", children: marketIndices.map((indexData) => (_jsx(MarketIndexCard, { data: indexData }, indexData.symbol))) }))] }), _jsxs("section", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h2", { className: "text-xl font-semibold text-slate-900", children: "Trending Stocks" }), _jsx("p", { className: "text-xs uppercase tracking-[0.16em] text-slate-500", children: "Volatility Radar" })] }), _jsx("div", { className: "grid gap-3 sm:grid-cols-2 xl:grid-cols-4", children: trendingStocks.map((stock) => (_jsx(StockCard, { data: stock }, stock.symbol))) })] }), _jsxs("section", { className: "space-y-3", children: [_jsx("h2", { className: "text-xl font-semibold text-slate-900", children: "Countries" }), _jsx("div", { className: "grid gap-4", children: countrySections.map((section) => (_jsx(CountrySection, { section: section }, section.country))) })] }), _jsxs("section", { className: "rounded-3xl border border-slate-200 bg-white p-5 shadow-sm", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900", children: "Connected Markets" }), _jsx("div", { className: "mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4", children: markets.slice(0, 8).map((market) => (_jsxs("article", { className: "rounded-xl border border-slate-200 bg-slate-50 p-4", children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-[0.14em] text-slate-500", children: market.code }), _jsx("p", { className: "mt-1 font-semibold text-slate-900", children: market.name }), _jsxs("p", { className: "mt-1 text-sm text-slate-600", children: [market.currency, " \u2022 ", market.timezone] })] }, market.code))) })] }), _jsx(SearchModal, {})] }));
}
